apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
data:
  DB_CONNECTION: pg
  DB_HOST: postgres-cluster-ip-service
  DB_PORT: '5432'
  DB_USER: postgres
  DB_PASSWORD: plain-password
  DB_DATABASE: tododb
